# Generated by Django 4.0.3 on 2022-08-06 21:48

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('promotions', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=apps.orders.models.Order.generate_code, editable=False, max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('Rejected', 'Rejected'), ('verifying', 'Verifying'), ('notverified', 'Notverified'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('fulfilled', 'Fulfilled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('reject_msg', models.TextField(blank=True, max_length=2000)),
                ('order_msg', models.TextField(blank=True, max_length=2000)),
                ('invalid_tracking_code_msg', models.TextField(blank=True, max_length=2000)),
                ('tracking_code', models.CharField(blank=True, max_length=20)),
                ('tracking_code_msg', models.CharField(blank=True, max_length=255)),
                ('cancel_msg', models.TextField(blank=True, max_length=2000)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('issue_return', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(blank=True, max_length=20)),
                ('coupon_type', models.CharField(blank=True, max_length=20)),
                ('coupon_percent', models.PositiveIntegerField(default=0)),
                ('coupon_amount', models.PositiveBigIntegerField(default=0)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('authority', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('pay_source', models.CharField(choices=[('wallet', 'Wallet'), ('direct', 'Direct')], max_length=20, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.coupon')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalogue.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAlternation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, help_text='tomans')),
                ('succeed', models.BooleanField(default=False, editable=False)),
                ('creditor_balance_type', models.CharField(choices=[('freezed', 'freezed'), ('available', 'available')], default='freezed', max_length=20)),
                ('debtor_balance_type', models.CharField(choices=[('freezed', 'freezed'), ('available', 'available')], default='freezed', max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('creditor', models.ForeignKey(blank=True, help_text='...lends money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyalternation', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(blank=True, help_text='... borrows money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellalternation', to=settings.AUTH_USER_MODEL)),
                ('intendant', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(blank=True, max_length=255)),
                ('prod_en_name', models.CharField(blank=True, max_length=255)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('sales_price', models.PositiveBigIntegerField(default=0)),
                ('has_sales', models.BooleanField(default=False)),
                ('final_price', models.PositiveBigIntegerField(default=0, help_text='total price after discount')),
                ('discount_code', models.CharField(blank=True, editable=False, max_length=8)),
                ('discount_pecent', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('free_shipping', models.BooleanField(default=False)),
                ('shipping_cost', models.PositiveBigIntegerField(default=0)),
                ('raced', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalogue.collection')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalogue.product')),
            ],
        ),
    ]
