# Generated by Django 4.0.3 on 2022-04-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_wallet_date_last_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('womamn', 'woman')], max_length=10),
        ),
    ]
