# Generated by Django 4.0.3 on 2022-04-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='freezed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
