# Generated by Django 4.0.3 on 2022-04-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_wallet_available_alter_wallet_freezed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman')], max_length=10),
        ),
    ]
