# Generated by Django 4.0.3 on 2022-04-22 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_committed', models.DateTimeField(default=django.utils.timezone.now)),
                ('succeeded', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='users.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_card', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('call_me', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(choices=[('inp', 'Inprogress'), ('ful', 'Fulfilled'), ('rej', 'Rejected')], default='inp', max_length=3)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_proceeded', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='users.wallet')),
            ],
        ),
    ]
