# Generated by Django 4.0.3 on 2022-04-24 07:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_deposittransaction_checkoutrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default=users.models.User.generate_usecode, editable=False, max_length=20),
        ),
    ]
