# Generated by Django 4.0.3 on 2022-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consumed_storage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
