# Generated by Django 4.0.3 on 2022-05-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_custom_storage_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposittransaction',
            old_name='succeeded',
            new_name='succeed',
        ),
    ]
