# Generated by Django 4.0.3 on 2022-05-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_ticket_ticketmessage_ticketreply_tickettype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
