# Generated by Django 4.0.3 on 2022-05-09 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
