# Generated by Django 4.0.3 on 2022-05-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_ticket_date_created_ticketreply_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seen',
            new_name='seen_by_intendant',
        ),
        migrations.RenameField(
            model_name='ticketreply',
            old_name='intendant',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='seen_by_intendant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
