# Generated by Django 4.0.3 on 2022-05-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_seen_ticket_seen_by_intendant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='titel',
            new_name='title',
        ),
    ]
