# Generated by Django 4.0.3 on 2022-05-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_titel_tickettype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.ticket'),
        ),
    ]
