# Generated by Django 4.0.3 on 2022-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_checkoutrequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(default='', max_length=255),
        ),
    ]
