# Generated by Django 4.0.3 on 2022-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_address_city_alter_address_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='authority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
