
site_name: OnMode
site_url: https://www.onmode.ir
nav:
  - Home: index.md
  - About: about.md
  - Architecture: architecture.md
  - Environment: environment.md
  - License: license.md
theme: readthedocs
