# Generated by Django 4.0.3 on 2022-04-22 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('NUM', 'Number'), ('TXT', 'Text'), ('BOL', 'Boolean'), ('CHO', 'Choices'), ('CHS', 'MultiChoices'), ('JSO', 'Json')], default='NUM', max_length=3)),
                ('default', models.CharField(blank=True, max_length=100)),
                ('choices', models.TextField(blank=True, max_length=10000)),
                ('meta', models.JSONField(default=dict)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('en_name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('en_slug', models.SlugField()),
                ('meta_description', models.CharField(max_length=144)),
                ('meta_keywords', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock_low_threshold', models.IntegerField(default=1)),
                ('free_shipping', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('sold_individually', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_sales', models.BooleanField(default=False)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_from', models.DateTimeField(null=True)),
                ('sales_to', models.DateTimeField(null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost_description', models.TextField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('attributes', models.JSONField(default=dict)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('options', models.ManyToManyField(related_name='products', to='catalogue.option')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=400)),
                ('address_description', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('product_capacity', models.PositiveIntegerField(default=100)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('fee', models.PositiveIntegerField(default=9)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('supported_provinces', models.CharField(blank=True, max_length=1000, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('fails', models.IntegerField(default=0)),
                ('rates_avg', models.FloatField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalogue.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.shop'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('en_name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('en_slug', models.SlugField()),
                ('meta_title', models.CharField(max_length=40)),
                ('meta_description', models.CharField(max_length=90)),
                ('description', models.TextField(max_length=2000)),
                ('prefer_collection_discount', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(related_name='collections', to='catalogue.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('en_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('en_slug', models.SlugField()),
                ('meta_title', models.CharField(max_length=90)),
                ('meta_keywords', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='catalogue.category')),
            ],
        ),
    ]
