# Generated by Django 4.0.3 on 2022-04-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_shop_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_from',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_to',
        ),
    ]
