# Generated by Django 4.0.3 on 2022-04-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_product_sales_from_remove_product_sales_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='supported_provinces',
        ),
    ]
