# Generated by Django 4.0.3 on 2022-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_createshoprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createshoprequest',
            old_name='status',
            new_name='reject_status',
        ),
        migrations.AddField(
            model_name='createshoprequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
