# Generated by Django 4.0.3 on 2022-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_producttype_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='shop',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
