# Generated by Django 4.0.3 on 2022-04-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_alter_category_options_shop_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ff', models.JSONField(default=dict)),
            ],
        ),
    ]
