# Generated by Django 4.0.3 on 2022-04-24 06:53

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_amodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=5000)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='catalogue.option')),
            ],
        ),
        migrations.DeleteModel(
            name='AModel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_code',
            field=models.CharField(default=catalogue.models.Product.generate_code, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalogue.product'),
        ),
    ]
