# Generated by Django 4.0.3 on 2022-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='description',
        ),
        migrations.RemoveField(
            model_name='option',
            name='meta',
        ),
        migrations.AddField(
            model_name='option',
            name='identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('NUM', 'Number'), ('TXT', 'Text'), ('BOL', 'Boolean'), ('CHO', 'Choices'), ('CHS', 'MultiChoices')], default='NUM', max_length=3),
        ),
    ]
