# Generated by Django 4.0.3 on 2022-04-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview', to='catalogue.photo'),
        ),
    ]
