# Generated by Django 4.0.3 on 2022-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_collection_index_poster_collection_index_poster_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='index_poster_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='page_poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
