# Generated by Django 4.0.3 on 2022-04-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('catalogue', '0023_collection_index_poster_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.discount'),
        ),
    ]
