# Generated by Django 4.0.3 on 2022-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_collection_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='index_poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='index_poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta_description',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta_title',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='collection',
            name='page_poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
