# Generated by Django 4.0.3 on 2022-04-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slogan',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
