# Generated by Django 4.0.3 on 2022-04-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_collection_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='index_poster_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='page_poster_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
