# Generated by Django 4.0.3 on 2022-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_collection_index_poster_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='index_view_count',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
