# Generated by Django 4.0.3 on 2022-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_collection_index_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured',
            field=models.ManyToManyField(related_name='featured', to='catalogue.product'),
        ),
    ]
