# Generated by Django 4.0.3 on 2022-04-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_collection_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured',
        ),
    ]
