# Generated by Django 4.0.3 on 2022-04-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_collection_featureds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='index_view_count',
        ),
    ]
