# Generated by Django 4.0.3 on 2022-04-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_remove_collection_index_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
