# Generated by Django 4.0.3 on 2022-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_alter_product_price_alter_product_sales_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_cost',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
