# Generated by Django 4.0.3 on 2022-05-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_favourite_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
