# Generated by Django 4.0.3 on 2022-05-02 08:46

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstats',
            name='product',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalogue.product'),
        ),
    ]
