# Generated by Django 4.0.3 on 2022-05-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstats',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalogue.product'),
        ),
    ]
