# Generated by Django 4.0.3 on 2022-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_comment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='fa_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
