# Generated by Django 4.0.3 on 2022-05-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_alter_product_en_name_alter_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='shop',
            name='meta_description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='shop',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
