# Generated by Django 4.0.3 on 2022-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user_custom_product_capacity',
            field=models.BooleanField(default=False),
        ),
    ]
