# Generated by Django 4.0.3 on 2022-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_alter_collection_en_slug_alter_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='en_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
