# Generated by Django 4.0.3 on 2022-05-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0052_alter_collection_index_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
