# Generated by Django 4.0.3 on 2022-05-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_shop_baner_shop_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='baner',
            new_name='banner',
        ),
    ]
