# Generated by Django 4.0.3 on 2022-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_rename_baner_shop_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='relateds',
            field=models.ManyToManyField(related_name='related_products', to='catalogue.product'),
        ),
    ]
