# Generated by Django 4.0.3 on 2022-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_product_relateds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='relateds',
            field=models.ManyToManyField(to='catalogue.product'),
        ),
    ]
