# Generated by Django 4.0.3 on 2022-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_alter_product_relateds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='catalogue.product'),
        ),
    ]
