# Generated by Django 4.0.3 on 2022-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_alter_collection_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collections', to='catalogue.product'),
        ),
    ]
