# Generated by Django 4.0.3 on 2022-09-07 16:11

import django.utils.timezone
from django.db import migrations, models

import apps.promotions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.promotions.models.Coupon.generate_code,
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("AM", "Amount"), ("PC", "Percent")],
                        default="PC",
                        max_length=2,
                    ),
                ),
                ("percent", models.PositiveIntegerField(default=0)),
                ("amount", models.PositiveBigIntegerField(default=0)),
                ("max_amount", models.PositiveBigIntegerField(default=10000)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_used",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_used",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                (
                    "code",
                    models.CharField(
                        default=apps.promotions.models.GiftCard.generate_code,
                        editable=False,
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
