# Generated by Django 4.0.3 on 2022-09-07 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="user",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
