# Generated by Django 4.0.3 on 2022-09-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preview",
                to="catalogue.photo",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="relateds",
            field=models.ManyToManyField(
                blank=True, null=True, to="catalogue.product"
            ),
        ),
    ]
