# Generated by Django 4.0.3 on 2022-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_product_preview_alter_product_relateds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='relateds',
            field=models.ManyToManyField(blank=True, to='catalogue.product'),
        ),
    ]
