# Generated by Django 4.0.3 on 2022-09-01 18:03

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_product_relateds"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("publisheds", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
