# Generated by Django 4.0.3 on 2022-04-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0021_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SliderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('click_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precedece', models.PositiveIntegerField(default=0)),
                ('collection_slider', models.BooleanField(default=False)),
                ('poster', models.ImageField(upload_to='')),
                ('poster_url', models.URLField(null=True)),
                ('tile_title', models.CharField(blank=True, max_length=255)),
                ('tile_slogan', models.CharField(blank=True, max_length=255)),
                ('tile_1_photo', models.ImageField(upload_to='')),
                ('tile_1_url', models.URLField()),
                ('tile_2', models.ImageField(upload_to='')),
                ('tile_2_url', models.URLField()),
                ('tile_3', models.ImageField(upload_to='')),
                ('tile_3_url', models.URLField()),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.collection')),
            ],
        ),
    ]
