# Generated by Django 4.0.3 on 2022-04-26 18:54

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_delete_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('favicon', models.ImageField(upload_to='')),
                ('site_title', models.CharField(blank=True, max_length=255)),
                ('site_description', models.TextField(blank=True, max_length=1000)),
                ('laws', django_quill.fields.QuillField()),
                ('abouts', django_quill.fields.QuillField()),
                ('pinned_message', models.CharField(blank=True, max_length=500)),
                ('pinned_color', models.CharField(blank=True, max_length=10)),
                ('pinned_text_color', models.CharField(blank=True, max_length=10)),
                ('jumbo_message', models.TextField(blank=True, max_length=1000)),
                ('jumbo_button_text', models.CharField(blank=True, max_length=50)),
                ('jumb_button_url', models.URLField(null=True)),
                ('tel_line_1', models.CharField(blank=True, max_length=20)),
                ('tel_line_2', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('instagram', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('telegram', models.URLField(null=True)),
                ('whatsapp', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
            ],
        ),
    ]
