# Generated by Django 4.0.3 on 2022-04-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
