# Generated by Django 4.0.3 on 2022-04-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_siteinfo_favicon_alter_siteinfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
