# Generated by Django 4.0.3 on 2022-04-26 19:03

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_siteinfo_facebook_alter_siteinfo_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='abouts',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='jumb_button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='laws',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
