# Generated by Django 4.0.3 on 2022-04-26 20:15

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_siteinfo_abouts_alter_siteinfo_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='section',
            old_name='tile_2',
            new_name='tile_2_photo',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='tile_3',
            new_name='tile_3_photo',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='abouts',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='laws',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='pinned_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sliderphoto',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sliderphoto',
            name='click_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MainStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.ManyToManyField(to='index.section')),
                ('slider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.slider')),
            ],
        ),
        migrations.AddField(
            model_name='sliderphoto',
            name='slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='index.slider'),
        ),
    ]
