# Generated by Django 4.0.3 on 2022-04-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_section_tile_button_text_section_tile_button_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSite',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='Laws',
            new_name='Law',
        ),
        migrations.RemoveField(
            model_name='mainstack',
            name='about',
        ),
        migrations.RemoveField(
            model_name='mainstack',
            name='laws',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
