# Generated by Django 4.0.3 on 2022-04-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_remove_section_collection_remove_sliderphoto_slider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderphoto',
            old_name='click_url',
            new_name='link',
        ),
    ]
