# Generated by Django 4.0.3 on 2022-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_rename_click_url_sliderphoto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
