# Generated by Django 4.0.3 on 2022-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_blogpost_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderphoto',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
