# Generated by Django 4.0.3 on 2022-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_sliderphoto_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
