# Generated by Django 4.0.3 on 2022-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_collection_index_poster_url_and_more'),
        ('index', '0016_alter_sliderphoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('shops', models.ManyToManyField(to='catalogue.shop')),
            ],
        ),
    ]
