# Generated by Django 4.0.3 on 2022-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_shopset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
