# Generated by Django 4.0.3 on 2022-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_blogpost_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='blog',
            field=models.URLField(blank=True, null=True),
        ),
    ]
