# Generated by Django 4.0.3 on 2022-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_siteinfo_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='show_jumbo_to',
            field=models.CharField(choices=[('All', 'All'), ('ShopKeeprs', 'ShopKeepers'), ('Customers', 'Customers')], default='All', max_length=20),
        ),
    ]
