# Generated by Django 4.0.3 on 2022-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_siteinfo_show_jumbo_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='show_jumbo_to',
            field=models.CharField(choices=[('All', 'All'), ('ShopKeeprs', 'ShopKeepers'), ('Customers', 'Customers'), ('GuestUser', 'GeustUser'), ('NoOne', 'NoOne')], default='All', max_length=20),
        ),
    ]
