# Generated by Django 4.0.3 on 2022-05-05 09:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_siteinfo_show_jumbo_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='law',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
