# Generated by Django 4.0.3 on 2022-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_about_content_alter_law_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=1000)),
                ('related_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
