# Generated by Django 4.0.3 on 2022-05-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_certificate_show_on_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='jumb_button_url',
            new_name='jumbo_button_url',
        ),
    ]
