# Generated by Django 4.0.3 on 2022-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_rename_jumb_button_url_siteinfo_jumbo_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
