# Generated by Django 4.0.3 on 2022-05-08 08:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_createshopguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrderGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
