# Generated by Django 4.0.3 on 2022-05-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_alter_blogpost_photo_alter_siteinfo_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='show_pinned_message',
            field=models.BooleanField(default=False),
        ),
    ]
