# Generated by Django 4.0.3 on 2022-05-28 15:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_siteinfo_show_pinned_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
