# Generated by Django 4.0.3 on 2022-04-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_collection_index_poster_url_and_more'),
        ('cart', '0003_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartitems', to='catalogue.collection'),
        ),
    ]
