# Generated by Django 4.0.3 on 2022-04-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='has_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sales_price',
            field=models.BooleanField(default=False),
        ),
    ]
