# Generated by Django 4.0.3 on 2022-04-29 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_alter_user_consumed_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0034_alter_product_price_alter_product_sales_price_and_more'),
        ('promotions', '0002_remove_coupon_reserved_discount_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=orders.models.Order.generate_code, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('Rejected', 'Rejected'), ('sent', 'Sent'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('notverified', 'Notverified'), ('canceled', 'Canceled'), ('fulfilled', 'Fulfilled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('reject_msg', models.TextField(max_length=2000)),
                ('tracking_code', models.CharField(blank=True, max_length=20)),
                ('tracking_code_msg', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fulfilled', models.DateTimeField(null=True)),
                ('issue_return', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(blank=True, max_length=20)),
                ('coupon_type', models.CharField(blank=True, max_length=20)),
                ('coupon_percent', models.PositiveIntegerField(default=0)),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.coupon')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalogue.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('sales_price', models.PositiveBigIntegerField(default=0)),
                ('has_sales', models.BooleanField(default=False)),
                ('final_price', models.PositiveBigIntegerField(default=0, help_text='total price after discount')),
                ('discount_code', models.CharField(blank=True, editable=False, max_length=8)),
                ('discount_pecent', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalogue.collection')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalogue.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fulfilled', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('proccessed', models.BooleanField(default=False)),
                ('fulfilled', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='orders.orderitem')),
                ('retutrn_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest')),
            ],
        ),
    ]
