# Generated by Django 4.0.3 on 2022-04-29 09:49

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_authority_order_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=orders.models.Order.generate_code, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='reject_msg',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
