# Generated by Django 4.0.3 on 2022-04-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_alter_product_price_alter_product_sales_price_and_more'),
        ('orders', '0006_alter_order_coupon_alter_order_date_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalogue.collection'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
