# Generated by Django 4.0.3 on 2022-04-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_collection_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='raced',
            field=models.BooleanField(default=False),
        ),
    ]
