# Generated by Django 4.0.3 on 2022-05-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_raced'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_msg',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_source',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('direct', 'Direct')], max_length=20, null=True),
        ),
    ]
