# Generated by Django 4.0.3 on 2022-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_order_msg_order_pay_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_msg',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='invalid_tracking_code_msg',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('Rejected', 'Rejected'), ('verifying', 'Verifying'), ('notverified', 'Notverified'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('fulfilled', 'Fulfilled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
