# Generated by Django 4.0.3 on 2022-05-07 09:19

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_cancel_msg_order_invalid_tracking_code_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(db_index=True, default=orders.models.Order.generate_code, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
