# Generated by Django 4.0.3 on 2022-05-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_code_alter_order_ref_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnRequestItem',
        ),
    ]
