# Generated by Django 4.0.3 on 2022-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_delete_returnrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prod_en_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prod_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
