# Generated by Django 4.0.3 on 2022-05-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_orderitem_prod_en_name_orderitem_prod_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAlternation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('succeed', models.BooleanField(default=False, editable=False)),
                ('creditor_balance_type', models.CharField(choices=[('freezed', 'freezed'), ('available', 'available')], default='freezed', max_length=20)),
                ('debtor_balance_type', models.CharField(choices=[('freezed', 'freezed'), ('available', 'available')], default='freezed', max_length=20)),
                ('creditor', models.ForeignKey(help_text='...lends money', on_delete=django.db.models.deletion.CASCADE, related_name='buyalternation', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(help_text='... borrows money', on_delete=django.db.models.deletion.CASCADE, related_name='sellalternation', to=settings.AUTH_USER_MODEL)),
                ('intendant', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
