# Generated by Django 4.0.3 on 2022-05-07 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_walletalternation'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletalternation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
