# Generated by Django 4.0.3 on 2022-05-07 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_walletalternation_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletalternation',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='walletalternation',
            name='creditor',
            field=models.ForeignKey(blank=True, help_text='...lends money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyalternation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='walletalternation',
            name='debtor',
            field=models.ForeignKey(blank=True, help_text='... borrows money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellalternation', to=settings.AUTH_USER_MODEL),
        ),
    ]
