# Generated by Django 4.0.3 on 2022-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_walletalternation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletalternation',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='tomans'),
        ),
    ]
