# Generated by Django 4.0.3 on 2022-09-07 16:11

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(null=True, upload_to="")),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "symbol",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("description", models.TextField(max_length=1000)),
                ("related_link", models.URLField(blank=True, null=True)),
                ("show_on_index", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ContactUsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="CreateShopGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="GeoLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provinces", models.JSONField()),
                ("cities", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="ReturnOrderGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("site_title", models.CharField(blank=True, max_length=255)),
                (
                    "site_description",
                    models.TextField(blank=True, max_length=1000),
                ),
                (
                    "pinned_message",
                    models.CharField(blank=True, max_length=500),
                ),
                ("pinned_color", models.CharField(blank=True, max_length=10)),
                (
                    "pinned_text_color",
                    models.CharField(blank=True, max_length=10),
                ),
                ("pinned_url", models.URLField(blank=True, null=True)),
                ("show_pinned_message", models.BooleanField(default=False)),
                (
                    "jumbo_message",
                    models.TextField(blank=True, max_length=1000),
                ),
                (
                    "jumbo_button_text",
                    models.CharField(blank=True, max_length=50),
                ),
                ("jumbo_button_url", models.URLField(blank=True, null=True)),
                (
                    "show_jumbo_to",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("ShopKeeprs", "ShopKeepers"),
                            ("Customers", "Customers"),
                            ("GuestUser", "GeustUser"),
                            ("NoOne", "NoOne"),
                        ],
                        default="All",
                        max_length=20,
                    ),
                ),
                ("tel_line_1", models.CharField(blank=True, max_length=20)),
                ("tel_line_2", models.CharField(blank=True, max_length=20)),
                ("mobile_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True, max_length=1000)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("blog", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("telegram", models.URLField(blank=True, null=True)),
                ("whatsapp", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("enable_GTM", models.BooleanField(default=False)),
                ("GOOGLE_TAG_ID", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(editable=False)),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name="SliderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="")),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("link", models.URLField(blank=True, null=True)),
                ("precedence", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ShopSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("slogan", models.CharField(blank=True, max_length=255)),
                ("shops", models.ManyToManyField(to="catalogue.shop")),
            ],
        ),
        migrations.CreateModel(
            name="ContactUsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True, max_length=5000)),
                ("read", models.BooleanField(default=False)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="index.contactustype",
                    ),
                ),
            ],
        ),
    ]
